-- Performance indexes: foreign keys, scope columns, and multi-tenant (organizationId, status) filters

CREATE INDEX IF NOT EXISTS "Container_branchId_idx" ON "Container"("branchId");
CREATE INDEX IF NOT EXISTS "MoveOutInspection_organizationId_status_idx" ON "MoveOutInspection"("organizationId", "status");
CREATE INDEX IF NOT EXISTS "TenantChecklist_templateId_idx" ON "TenantChecklist"("templateId");
CREATE INDEX IF NOT EXISTS "TenantChecklist_status_idx" ON "TenantChecklist"("status");
CREATE INDEX IF NOT EXISTS "RentalApplication_status_idx" ON "RentalApplication"("status");
CREATE INDEX IF NOT EXISTS "MonthlyRentSummary_branchId_idx" ON "MonthlyRentSummary"("branchId");
CREATE INDEX IF NOT EXISTS "UserRoleContext_organizationId_idx" ON "UserRoleContext"("organizationId");
CREATE INDEX IF NOT EXISTS "UserRoleContext_containerId_idx" ON "UserRoleContext"("containerId");
CREATE INDEX IF NOT EXISTS "ServiceEnquiry_organizationId_idx" ON "ServiceEnquiry"("organizationId");
CREATE INDEX IF NOT EXISTS "ServiceEnquiry_userId_idx" ON "ServiceEnquiry"("userId");
CREATE INDEX IF NOT EXISTS "ServiceEnquiry_assignedTo_idx" ON "ServiceEnquiry"("assignedTo");
CREATE INDEX IF NOT EXISTS "ServiceEnquiry_organizationId_status_idx" ON "ServiceEnquiry"("organizationId", "status");
CREATE INDEX IF NOT EXISTS "ShortStayBooking_organizationId_status_idx" ON "ShortStayBooking"("organizationId", "status");
CREATE INDEX IF NOT EXISTS "BookingStockUsage_stockItemId_idx" ON "BookingStockUsage"("stockItemId");
CREATE INDEX IF NOT EXISTS "ServiceRequest_branchId_idx" ON "ServiceRequest"("branchId");
CREATE INDEX IF NOT EXISTS "ServiceRequest_unitId_idx" ON "ServiceRequest"("unitId");
CREATE INDEX IF NOT EXISTS "ServiceRequest_createdBy_idx" ON "ServiceRequest"("createdBy");
CREATE INDEX IF NOT EXISTS "ServiceRequest_organizationId_status_idx" ON "ServiceRequest"("organizationId", "status");
CREATE INDEX IF NOT EXISTS "Lease_organizationId_idx" ON "Lease"("organizationId");
CREATE INDEX IF NOT EXISTS "Lease_branchId_idx" ON "Lease"("branchId");
CREATE INDEX IF NOT EXISTS "Lease_unitId_idx" ON "Lease"("unitId");
CREATE INDEX IF NOT EXISTS "Lease_propertyId_idx" ON "Lease"("propertyId");
CREATE INDEX IF NOT EXISTS "Lease_createdBy_idx" ON "Lease"("createdBy");
CREATE INDEX IF NOT EXISTS "Lease_organizationId_status_idx" ON "Lease"("organizationId", "status");
CREATE INDEX IF NOT EXISTS "ProfessionalProfile_branchId_idx" ON "ProfessionalProfile"("branchId");
CREATE INDEX IF NOT EXISTS "ProfessionalProfile_userId_idx" ON "ProfessionalProfile"("userId");
CREATE INDEX IF NOT EXISTS "AuditLog_branchId_idx" ON "AuditLog"("branchId");
CREATE INDEX IF NOT EXISTS "AuditLog_userId_idx" ON "AuditLog"("userId");
CREATE INDEX IF NOT EXISTS "Transaction_fromWalletId_idx" ON "Transaction"("fromWalletId");
CREATE INDEX IF NOT EXISTS "Transaction_toWalletId_idx" ON "Transaction"("toWalletId");
CREATE INDEX IF NOT EXISTS "Transaction_unitId_idx" ON "Transaction"("unitId");
CREATE INDEX IF NOT EXISTS "Transaction_propertyId_idx" ON "Transaction"("propertyId");
CREATE INDEX IF NOT EXISTS "Transaction_organizationId_status_idx" ON "Transaction"("organizationId", "status");
CREATE INDEX IF NOT EXISTS "EscrowAccount_tenantId_idx" ON "EscrowAccount"("tenantId");
CREATE INDEX IF NOT EXISTS "EscrowAccount_unitId_idx" ON "EscrowAccount"("unitId");
CREATE INDEX IF NOT EXISTS "EscrowAccount_propertyId_idx" ON "EscrowAccount"("propertyId");
CREATE INDEX IF NOT EXISTS "EscrowAccount_status_idx" ON "EscrowAccount"("status");
CREATE INDEX IF NOT EXISTS "FundHold_walletId_idx" ON "FundHold"("walletId");
CREATE INDEX IF NOT EXISTS "RentInvoice_tenantId_idx" ON "RentInvoice"("tenantId");
CREATE INDEX IF NOT EXISTS "RentInvoice_unitId_idx" ON "RentInvoice"("unitId");
CREATE INDEX IF NOT EXISTS "RentInvoice_propertyId_idx" ON "RentInvoice"("propertyId");
CREATE INDEX IF NOT EXISTS "RentInvoice_status_idx" ON "RentInvoice"("status");
CREATE INDEX IF NOT EXISTS "ReconciliationReport_status_idx" ON "ReconciliationReport"("status");
CREATE INDEX IF NOT EXISTS "Unit_branchId_idx" ON "Unit"("branchId");
CREATE INDEX IF NOT EXISTS "Unit_propertyId_idx" ON "Unit"("propertyId");
CREATE INDEX IF NOT EXISTS "Unit_organizationId_status_idx" ON "Unit"("organizationId", "status");
CREATE INDEX IF NOT EXISTS "Property_branchId_idx" ON "Property"("branchId");
CREATE INDEX IF NOT EXISTS "Property_ownerUserId_idx" ON "Property"("ownerUserId");
CREATE INDEX IF NOT EXISTS "Property_managerUserId_idx" ON "Property"("managerUserId");
CREATE INDEX IF NOT EXISTS "Property_createdBy_idx" ON "Property"("createdBy");
CREATE INDEX IF NOT EXISTS "Property_organizationId_status_idx" ON "Property"("organizationId", "status");
CREATE INDEX IF NOT EXISTS "AppUser_status_idx" ON "AppUser"("status");
CREATE INDEX IF NOT EXISTS "RolePermission_permissionId_idx" ON "RolePermission"("permissionId");
CREATE INDEX IF NOT EXISTS "UserRoleAssignment_roleId_idx" ON "UserRoleAssignment"("roleId");
CREATE INDEX IF NOT EXISTS "UserRoleAssignment_branchId_idx" ON "UserRoleAssignment"("branchId");
CREATE INDEX IF NOT EXISTS "UserRoleAssignment_organizationId_status_idx" ON "UserRoleAssignment"("organizationId", "status");
CREATE INDEX IF NOT EXISTS "KycDocument_organizationId_idx" ON "KycDocument"("organizationId");
CREATE INDEX IF NOT EXISTS "KycDocument_branchId_idx" ON "KycDocument"("branchId");
CREATE INDEX IF NOT EXISTS "KycDocument_organizationId_status_idx" ON "KycDocument"("organizationId", "status");
CREATE INDEX IF NOT EXISTS "Expense_branchId_idx" ON "Expense"("branchId");
CREATE INDEX IF NOT EXISTS "Expense_unitId_idx" ON "Expense"("unitId");
CREATE INDEX IF NOT EXISTS "Expense_propertyId_idx" ON "Expense"("propertyId");
CREATE INDEX IF NOT EXISTS "Expense_createdBy_idx" ON "Expense"("createdBy");
CREATE INDEX IF NOT EXISTS "FinancialReport_branchId_idx" ON "FinancialReport"("branchId");
CREATE INDEX IF NOT EXISTS "FinancialReport_propertyId_idx" ON "FinancialReport"("propertyId");
CREATE INDEX IF NOT EXISTS "LeaseRenewalAlert_unitId_idx" ON "LeaseRenewalAlert"("unitId");
CREATE INDEX IF NOT EXISTS "LeaseRenewalAlert_propertyId_idx" ON "LeaseRenewalAlert"("propertyId");
CREATE INDEX IF NOT EXISTS "LeaseRenewalAlert_leaseId_idx" ON "LeaseRenewalAlert"("leaseId");
CREATE INDEX IF NOT EXISTS "LeaseRenewalAlert_status_idx" ON "LeaseRenewalAlert"("status");
CREATE INDEX IF NOT EXISTS "UserSubscription_organizationId_idx" ON "UserSubscription"("organizationId");
CREATE INDEX IF NOT EXISTS "UserSubscription_userId_idx" ON "UserSubscription"("userId");
CREATE INDEX IF NOT EXISTS "UserSubscription_organizationId_status_idx" ON "UserSubscription"("organizationId", "status");
CREATE INDEX IF NOT EXISTS "TenantScreeningReport_applicationId_idx" ON "TenantScreeningReport"("applicationId");
CREATE INDEX IF NOT EXISTS "TenantScreeningReport_status_idx" ON "TenantScreeningReport"("status");
CREATE INDEX IF NOT EXISTS "ESignRequest_leaseId_idx" ON "ESignRequest"("leaseId");
CREATE INDEX IF NOT EXISTS "ESignRequest_createdBy_idx" ON "ESignRequest"("createdBy");
CREATE INDEX IF NOT EXISTS "ESignRequest_templateId_idx" ON "ESignRequest"("templateId");
CREATE INDEX IF NOT EXISTS "ESignRequest_status_idx" ON "ESignRequest"("status");
CREATE INDEX IF NOT EXISTS "ReminderSchedule_organizationId_idx" ON "ReminderSchedule"("organizationId");
CREATE INDEX IF NOT EXISTS "ReminderSchedule_branchId_idx" ON "ReminderSchedule"("branchId");
CREATE INDEX IF NOT EXISTS "TeamInvitation_branchId_idx" ON "TeamInvitation"("branchId");
CREATE INDEX IF NOT EXISTS "ServiceRequestQuote_status_idx" ON "ServiceRequestQuote"("status");
CREATE INDEX IF NOT EXISTS "OutboxEvent_serviceRequestId_idx" ON "OutboxEvent"("serviceRequestId");
CREATE INDEX IF NOT EXISTS "UserPackageSubscription_packageId_idx" ON "UserPackageSubscription"("packageId");
CREATE INDEX IF NOT EXISTS "UserPackageSubscription_organizationId_status_idx" ON "UserPackageSubscription"("organizationId", "status");
CREATE INDEX IF NOT EXISTS "FreezeAppeal_status_idx" ON "FreezeAppeal"("status");
CREATE INDEX IF NOT EXISTS "UtilityReading_createdBy_idx" ON "UtilityReading"("createdBy");
CREATE INDEX IF NOT EXISTS "UtilityDispute_status_idx" ON "UtilityDispute"("status");
CREATE INDEX IF NOT EXISTS "DataImportJob_branchId_idx" ON "DataImportJob"("branchId");
CREATE INDEX IF NOT EXISTS "DataImportJob_createdBy_idx" ON "DataImportJob"("createdBy");
CREATE INDEX IF NOT EXISTS "PastRentRecord_unitId_idx" ON "PastRentRecord"("unitId");
CREATE INDEX IF NOT EXISTS "PastRentRecord_propertyId_idx" ON "PastRentRecord"("propertyId");
CREATE INDEX IF NOT EXISTS "RentReceipt_unitId_idx" ON "RentReceipt"("unitId");
CREATE INDEX IF NOT EXISTS "RentReceipt_propertyId_idx" ON "RentReceipt"("propertyId");
CREATE INDEX IF NOT EXISTS "PropertyTransferRecord_createdBy_idx" ON "PropertyTransferRecord"("createdBy");
CREATE INDEX IF NOT EXISTS "ComplianceNumber_unitId_idx" ON "ComplianceNumber"("unitId");
CREATE INDEX IF NOT EXISTS "ComplianceNumber_propertyId_idx" ON "ComplianceNumber"("propertyId");
CREATE INDEX IF NOT EXISTS "ComplianceNumber_organizationId_status_idx" ON "ComplianceNumber"("organizationId", "status");
CREATE INDEX IF NOT EXISTS "ComplianceRecord_status_idx" ON "ComplianceRecord"("status");
CREATE INDEX IF NOT EXISTS "DepositTransfer_propertyId_idx" ON "DepositTransfer"("propertyId");
CREATE INDEX IF NOT EXISTS "DepositTransfer_leaseId_idx" ON "DepositTransfer"("leaseId");
