import type { ProfileMockDataset } from "@/types/profile-system";

/**
 * Dummy relational data for the profile architecture (Phase 1).
 * In production this becomes DB migrations + seed scripts.
 */
export const profileMockDataset: ProfileMockDataset = {
  roles: [
    {
      id: "role_super_admin",
      slug: "super_admin",
      displayName: "Super Admin",
      isInternal: true,
      isPublicDirectoryEligible: false,
      sortOrder: 1,
    },
    {
      id: "role_supervisor",
      slug: "supervisor",
      displayName: "Supervisor",
      isInternal: true,
      isPublicDirectoryEligible: false,
      sortOrder: 2,
    },
    {
      id: "role_staff",
      slug: "staff",
      displayName: "Staff",
      isInternal: true,
      isPublicDirectoryEligible: false,
      sortOrder: 3,
    },
    {
      id: "role_landlord",
      slug: "landlord",
      displayName: "Landlord",
      isInternal: false,
      isPublicDirectoryEligible: false,
      sortOrder: 10,
    },
    {
      id: "role_tenant",
      slug: "tenant",
      displayName: "Tenant",
      isInternal: false,
      isPublicDirectoryEligible: false,
      sortOrder: 11,
    },
    {
      id: "role_buyer",
      slug: "buyer",
      displayName: "Buyer",
      isInternal: false,
      isPublicDirectoryEligible: false,
      sortOrder: 12,
    },
    {
      id: "role_seller",
      slug: "seller",
      displayName: "Seller",
      isInternal: false,
      isPublicDirectoryEligible: false,
      sortOrder: 13,
    },
    {
      id: "role_professional",
      slug: "professional",
      displayName: "Professional",
      isInternal: false,
      isPublicDirectoryEligible: true,
      sortOrder: 20,
    },
    {
      id: "role_service_provider",
      slug: "service_provider",
      displayName: "Service Provider",
      isInternal: false,
      isPublicDirectoryEligible: true,
      sortOrder: 21,
    },
    {
      id: "role_external_client",
      slug: "external_client",
      displayName: "External Client",
      isInternal: false,
      isPublicDirectoryEligible: false,
      sortOrder: 30,
    },
  ],

  users: [
    {
      id: "u1",
      email: "david@secureliving.com",
      status: "active",
      createdAt: "2025-01-10T08:00:00.000Z",
    },
    {
      id: "u2",
      email: "kevin@secureliving.com",
      status: "active",
      createdAt: "2025-01-05T08:00:00.000Z",
    },
    {
      id: "u3",
      email: "sarah@secureliving.com",
      status: "active",
      createdAt: "2025-02-01T08:00:00.000Z",
    },
    {
      id: "u4",
      email: "wanjiku@mwakaba.co.ke",
      status: "active",
      createdAt: "2025-03-01T08:00:00.000Z",
    },
    {
      id: "u5",
      email: "grace@kenyarealtors.co.ke",
      status: "active",
      createdAt: "2025-02-15T08:00:00.000Z",
    },
    {
      id: "u6",
      email: "amina@diasporalink.com",
      status: "active",
      createdAt: "2025-04-01T08:00:00.000Z",
    },
    {
      id: "u7",
      email: "james@secureliving.com",
      status: "active",
      createdAt: "2025-05-01T08:00:00.000Z",
    },
  ],

  userRoles: [
    {
      id: "ur_u1_landlord",
      userId: "u1",
      roleId: "role_landlord",
      organizationId: "org1",
      branchId: "b1",
      status: "active",
      permissions: [
        "properties:view",
        "properties:edit",
        "transactions:release",
      ],
      assignedAt: "2025-01-10T09:00:00.000Z",
    },
    {
      id: "ur_u1_professional",
      userId: "u1",
      roleId: "role_professional",
      organizationId: "org1",
      branchId: "b1",
      status: "active",
      permissions: ["services:view", "services:update_assigned"],
      assignedAt: "2025-06-01T09:00:00.000Z",
    },
    {
      id: "ur_u2_super_admin",
      userId: "u2",
      roleId: "role_super_admin",
      organizationId: "org0",
      branchId: "b0",
      status: "active",
      permissions: ["*"],
      assignedAt: "2025-01-05T09:00:00.000Z",
    },
    {
      id: "ur_u3_tenant",
      userId: "u3",
      roleId: "role_tenant",
      organizationId: "org1",
      branchId: "b1",
      status: "active",
      permissions: ["tenants:view_own", "properties:view", "property:create"],
      assignedAt: "2025-02-01T10:00:00.000Z",
    },
    {
      id: "ur_u4_staff",
      userId: "u4",
      roleId: "role_staff",
      organizationId: "org1",
      branchId: "b1",
      status: "active",
      permissions: [
        "properties:view",
        "tenants:view_branch",
        "kyc:review",
      ],
      assignedAt: "2025-03-01T10:00:00.000Z",
    },
    {
      id: "ur_u5_supervisor",
      userId: "u5",
      roleId: "role_supervisor",
      organizationId: "org2",
      branchId: "b3",
      status: "active",
      permissions: [
        "properties:view",
        "tenants:view_branch",
        "reports:branch",
      ],
      assignedAt: "2025-02-15T11:00:00.000Z",
    },
    {
      id: "ur_u6_external",
      userId: "u6",
      roleId: "role_external_client",
      organizationId: "org3",
      branchId: "b6",
      status: "active",
      permissions: ["portal:limited"],
      assignedAt: "2025-04-01T12:00:00.000Z",
    },
    {
      id: "ur_u6_buyer",
      userId: "u6",
      roleId: "role_buyer",
      organizationId: "org3",
      branchId: "b6",
      status: "active",
      permissions: ["marketplace:buyer"],
      assignedAt: "2025-04-15T12:00:00.000Z",
    },
    {
      id: "ur_u7_service_provider",
      userId: "u7",
      roleId: "role_service_provider",
      organizationId: "org1",
      branchId: "b1",
      status: "active",
      permissions: ["services:contractor_admin"],
      assignedAt: "2025-05-01T09:00:00.000Z",
    },
    {
      id: "ur_u7_seller",
      userId: "u7",
      roleId: "role_seller",
      organizationId: "org1",
      branchId: "b1",
      status: "active",
      permissions: ["marketplace:seller"],
      assignedAt: "2025-05-01T09:30:00.000Z",
    },
  ],

  profiles: [
    {
      userId: "u1",
      displayName: "David Mwakaba",
      givenName: "David",
      familyName: "Mwakaba",
      avatarUrl: "https://i.pravatar.cc/300?img=12",
      locale: "en-KE",
      timezone: "Africa/Nairobi",
      phone: "+254 712 555 010",
      city: "Nairobi",
      country: "Kenya",
      mailingAddress: "P.O. Box 44100-00100, Nairobi",
      bio: "Independent landlord with units in Westlands and Kilimani; diaspora coordination via Secure Living.",
    },
    {
      userId: "u2",
      displayName: "Kevin P.",
      givenName: "Kevin",
      avatarUrl: "https://i.pravatar.cc/300?img=15",
      locale: "en-KE",
      timezone: "Africa/Nairobi",
      phone: "+254 700 111 333",
      country: "Kenya",
    },
    {
      userId: "u3",
      displayName: "Sarah K.",
      givenName: "Sarah",
      avatarUrl: "https://i.pravatar.cc/300?img=47",
      locale: "en-KE",
      timezone: "Africa/Nairobi",
      phone: "+254 711 444 555",
      city: "Nairobi",
      country: "Kenya",
      mailingAddress: "Riverside Drive, Nairobi",
    },
    {
      userId: "u4",
      displayName: "Wanjiku N.",
      givenName: "Wanjiku",
      avatarUrl: "https://i.pravatar.cc/300?img=32",
      locale: "en-KE",
      timezone: "Africa/Nairobi",
      phone: "+254 722 100 200",
      city: "Nairobi",
      country: "Kenya",
    },
    {
      userId: "u5",
      displayName: "Grace Muthoni",
      givenName: "Grace",
      familyName: "Muthoni",
      avatarUrl: "https://i.pravatar.cc/300?img=5",
      locale: "en-KE",
      timezone: "Africa/Nairobi",
      phone: "+254 733 200 300",
      city: "Nairobi",
      country: "Kenya",
    },
    {
      userId: "u6",
      displayName: "Amina Hassan",
      givenName: "Amina",
      familyName: "Hassan",
      avatarUrl: "https://i.pravatar.cc/300?img=26",
      locale: "en-GB",
      timezone: "Europe/London",
      phone: "+44 7700 900123",
      city: "London",
      country: "United Kingdom",
    },
    {
      userId: "u7",
      displayName: "James Otieno",
      givenName: "James",
      familyName: "Otieno",
      avatarUrl: "https://i.pravatar.cc/300?img=53",
      locale: "en-KE",
      timezone: "Africa/Nairobi",
      phone: "+254 711 300 400",
      city: "Mombasa",
      country: "Kenya",
    },
  ],

  landlordProfiles: [
    {
      userRoleId: "ur_u1_landlord",
      userId: "u1",
      companyName: "Mwakaba Properties",
      taxPin: "A01234****",
      defaultPortfolioId: "pf_u1_main",
    },
  ],

  tenantProfiles: [
    {
      userRoleId: "ur_u3_tenant",
      userId: "u3",
      kycTier: "standard",
      currentLeaseId: "lease_demo_1",
    },
  ],

  staffProfiles: [
    {
      userRoleId: "ur_u2_super_admin",
      userId: "u2",
      employeeId: "EMP-001",
      department: "Platform",
      jobTitle: "Platform Super Admin",
      reportsToUserId: null,
    },
    {
      userRoleId: "ur_u4_staff",
      userId: "u4",
      employeeId: "EMP-104",
      department: "Operations",
      jobTitle: "Branch Operations",
      reportsToUserId: "u1",
    },
    {
      userRoleId: "ur_u5_supervisor",
      userId: "u5",
      employeeId: "EMP-220",
      department: "Agency Supervision",
      jobTitle: "Branch Supervisor",
      reportsToUserId: null,
    },
  ],

  professionalProfiles: [
    {
      userRoleId: "ur_u1_professional",
      userId: "u1",
      publicSlug: "david-mwakaba-electrical",
      headline: "Certified electrical & smart-home installations",
      isPublic: true,
      verificationStatus: "verified",
      yearsExperience: 12,
    },
  ],

  serviceProviderProfiles: [
    {
      userRoleId: "ur_u7_service_provider",
      userId: "u7",
      businessLegalName: "Coastal Field Services Ltd",
      registrationNumber: "BN/2024/889921",
      publicSlug: "coastal-field-services",
      isPublic: true,
      primaryContactUserId: "u7",
    },
  ],

  externalClientProfiles: [
    {
      userRoleId: "ur_u6_external",
      userId: "u6",
      relationshipType: "diaspora_coordination",
      referralSource: "partner_agency",
    },
  ],

  buyerProfiles: [
    {
      userRoleId: "ur_u6_buyer",
      userId: "u6",
      searchBrief: "2BR near Westlands or Kilimani, budget up to KES 120k/mo",
      agentUserId: null,
    },
  ],

  sellerProfiles: [
    {
      userRoleId: "ur_u7_seller",
      userId: "u7",
      listingPreferences: "Off-market handovers preferred; escrow via Secure Living.",
    },
  ],

  profileAttributes: [
    {
      id: "pa_u1_1",
      userId: "u1",
      userRoleId: null,
      namespace: "preferences",
      key: "whatsapp_number",
      valueText: "+254 712 555 010",
      updatedAt: "2025-01-11T08:00:00.000Z",
    },
    {
      id: "pa_u1_2",
      userId: "u1",
      namespace: "preferences",
      key: "preferred_currency",
      valueText: "KES",
      updatedAt: "2025-01-11T08:00:00.000Z",
    },
    {
      id: "pa_u1_3",
      userId: "u1",
      userRoleId: "ur_u1_landlord",
      namespace: "compliance",
      key: "last_kyc_refresh",
      valueJson: { at: "2025-12-01", level: "org" },
      updatedAt: "2025-12-01T10:00:00.000Z",
    },
    {
      id: "pa_u3_1",
      userId: "u3",
      namespace: "preferences",
      key: "preferred_language",
      valueText: "English",
      updatedAt: "2025-02-02T08:00:00.000Z",
    },
    {
      id: "pa_u3_2",
      userId: "u3",
      namespace: "emergency",
      key: "contact",
      valueJson: {
        name: "Mary K.",
        phone: "+254 733 888 999",
      },
      updatedAt: "2025-02-02T08:00:00.000Z",
    },
  ],
};
